/* (c) Magnus Auvinen. See licence.txt in the root of the distribution for more information. */
/* If you are missing that file, acquire a complete release at teeworlds.com.                */
#include <base/hash_ctxt.h>
#include <base/system.h>

#include "uuid.h"

static const Uuid TEEWORLDS_NAMESPACE = {{// "e05ddaaa-c4e6-4cfb-b642-5d48e80c0029"
	0xe0, 0x5d, 0xda, 0xaa, 0xc4, 0xe6, 0x4c, 0xfb,
	0xb6, 0x42, 0x5d, 0x48, 0xe8, 0x0c, 0x00, 0x29}};

const Uuid UUID_ZEROED = {{// "00000000-0000-0000-0000-000000000000"
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}};

Uuid random_uuid()
{
	Uuid Result;
	secure_random_fill(&Result, sizeof(Result));

	// set version 4 (UUID is randomly generated)
	Result.m_aData[6] &= 0x0f;
	Result.m_aData[6] |= 0x40;

	// set variant 1 (RFC 4122)
	Result.m_aData[8] &= 0x3f;
	Result.m_aData[8] |= 0x80;

	return Result;
}

Uuid calculate_uuid(const char *name)
{
	MD5_CTX Md5;
	MD5_DIGEST Digest;
	Uuid Result;

	md5_init(&Md5);
	md5_update(&Md5, TEEWORLDS_NAMESPACE.m_aData, sizeof(TEEWORLDS_NAMESPACE.m_aData));
	// Without terminating NUL.
	md5_update(&Md5, name, str_length(name));

	Digest = md5_finish(&Md5);

	for(unsigned i = 0; i < sizeof(Result.m_aData); i++)
	{
		Result.m_aData[i] = Digest.data[i];
	}

	// set version 3 (UUID is generated by MD5 hashing a namespace identifier and a name)
	Result.m_aData[6] &= 0x0f;
	Result.m_aData[6] |= 0x30;

	// set variant 1 (RFC 4122)
	Result.m_aData[8] &= 0x3f;
	Result.m_aData[8] |= 0x80;

	return Result;
}

void format_uuid(Uuid uuid, char *buffer, int size)
{
	unsigned char *p = uuid.m_aData;
	str_format(buffer, size,
		"%02x%02x%02x%02x-%02x%02x-%02x%02x-%02x%02x-%02x%02x%02x%02x%02x%02x",
		p[0], p[1], p[2], p[3], p[4], p[5], p[6], p[7],
		p[8], p[9], p[10], p[11], p[12], p[13], p[14], p[15]);
}

int uuid_comp(Uuid uuid1, Uuid uuid2)
{
	return mem_comp(uuid1.m_aData, uuid2.m_aData, sizeof(uuid1.m_aData));
}

int parse_uuid(Uuid *uuid, const char *buffer)
{
	char copy[UUID_MAXSTRSIZE];
	if(str_length(buffer) + 1 != UUID_MAXSTRSIZE)
	{
		return 2;
	}
	str_copy(copy, buffer, sizeof(copy));
	// 01234567-9012-4567-9012-456789012345
	if(copy[8] != '-' || copy[13] != '-' || copy[18] != '-' || copy[23] != '-')
	{
		return 1;
	}
	copy[8] = copy[13] = copy[18] = copy[23] = 0;
	if(str_hex_decode(uuid->m_aData + 0, 4, copy + 0) ||
		str_hex_decode(uuid->m_aData + 4, 2, copy + 9) ||
		str_hex_decode(uuid->m_aData + 6, 2, copy + 14) ||
		str_hex_decode(uuid->m_aData + 8, 2, copy + 19) ||
		str_hex_decode(uuid->m_aData + 10, 6, copy + 24))
	{
		return 1;
	}
	return 0;
}
